package xyz.nulldev.ts.api.v3.models.exceptions

enum class WErrorTypes {
    NAME_CONFLICT,
    ORDER_CONFLICT,
    AUTH_UNSUPPORTED,
    ALREADY_LOGGED_IN,
    INVALID_TYPE,
    NO_MANGA,
    NO_COVER,
    NO_SOURCE,
    NO_CATEGORY,
    MANGA_INFO_UPDATE_FAILED,
    COVER_DOWNLOAD_ERROR,
    UNKNOWN_FLAG_VALUE,
    UNKNOWN_MANGA_STATUS,
    UNKNOWN_MANGA_VIEWER,
    NON_CATALOGUE_SOURCE,
    FILTER_DESERIALIZATION_FAILED,
    LATEST_UPDATES_UNSUPPORTED,
    CATALOGUE_FETCH_ERROR
}